spring:
  profiles.active: local

  datasource:
    url: ${JDBC_CONNECTION_STRING:jdbc:mysql://localhost/chichart}
    username: ${JDBC_USER:chichart}
    password: ${JDBC_PASSWORD:chichart}
    name: chichart
    # default mysql driver version for Spring Boot 2 is 8.x. We have reverted back to 5.1.47, as my dev box has MySQL 5.x
    # to use 8, remove the driverclassname property here and also remove/change mysql.version in pom.xml
    driverclassname: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  flyway:
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: true
    locations:
      - classpath:db/migration

  h2.console.enabled: false

server:
  port: 8080

registration:
  trialPeriodDays: 14
